#!/usr/bin/env python3
"""Build a ZWASM .zgame package from a game directory."""

from __future__ import annotations

import argparse
import datetime as dt
import fnmatch
import gzip
import hashlib
import json
import shutil
import tempfile
from pathlib import Path, PurePosixPath
import struct
from typing import Iterable

MAGIC = b"ZWASMG01"
VERSION = 1
HEADER_SIZE = 64
PAGE_SIZE = 4096
HEADER = struct.Struct("<8sIIQQQI20s")

NATIVE_SUFFIXES = {
    ".exe", ".dll", ".sys", ".drv", ".ocx", ".pdb", ".lib", ".obj",
    ".exp", ".ilk", ".scr", ".cpl",
}
SKIP_DIRS = {
    ".git", ".hg", ".svn", "__pycache__", ".vs", ".idea", "dist",
    "save", "saves", "savedata", "userdata", "logs", "log",
    "tmp", "temp", "cache", "crashdumps",
    # generated by tools/zwasm_build.py; packaged through explicit roles instead
    ".zwasm", "zwasm_guest",
}
SKIP_SUFFIXES = {".zgame"}


class PackageError(RuntimeError):
    pass


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def safe_rel(path: Path, root: Path) -> str:
    rel = path.relative_to(root).as_posix()
    pp = PurePosixPath(rel)
    if pp.is_absolute() or ".." in pp.parts:
        raise PackageError("unsafe package path: " + rel)
    return rel


def should_skip(rel: str, include_native: bool, excludes: list[str]) -> bool:
    parts = PurePosixPath(rel).parts
    if any(p.lower() in SKIP_DIRS for p in parts[:-1]):
        return True
    suffix = PurePosixPath(rel).suffix.lower()
    if suffix in SKIP_SUFFIXES:
        return True
    if not include_native and suffix in NATIVE_SUFFIXES:
        return True
    return any(fnmatch.fnmatch(rel, pat) for pat in excludes)


def iter_instance_files(
    root: Path, include_native: bool, excludes: list[str]
) -> Iterable[tuple[str, Path]]:
    for path in sorted(root.rglob("*")):
        if not path.is_file():
            continue
        rel = safe_rel(path, root)
        if should_skip(rel, include_native, excludes):
            continue
        yield "instance/" + rel, path


def choose_compression(
    data: bytes, policy: str, threshold: int
) -> tuple[str, bytes]:
    if policy == "never":
        return "none", data
    if policy not in {"auto", "always"}:
        raise PackageError("unknown compression policy: " + policy)
    if policy == "auto" and len(data) > threshold:
        return "none", data
    out = gzip.compress(data, compresslevel=6, mtime=0)
    if policy == "auto" and len(out) >= len(data):
        return "none", data
    return "gzip", out


def default_output(input_dir: Path) -> Path:
    stem = input_dir.name.replace(" ", ".")
    for c in '<>:"/\\|?*':
        stem = stem.replace(c, "_")
    return Path("dist") / (stem + ".zgame")


def resolve_role(
    root: Path,
    supplied: str | None,
    role: str,
    explicit_name: str,
    discovered_names: tuple[str, ...],
) -> tuple[Path | None, str | None]:
    if supplied:
        path = Path(supplied).resolve()
        if not path.is_file():
            raise PackageError(role + " file does not exist: " + str(path))
        return path, explicit_name

    for name in discovered_names:
        path = (root / name).resolve()
        if path.is_file():
            return path, path.name
    return None, None


def hash_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(8 * 1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def prepare_payload(
    source: Path,
    policy: str,
    threshold: int,
    temp_dir: Path,
    token: int,
) -> tuple[str, Path, int, int, str]:
    source_size = source.stat().st_size
    if policy == "never" or (policy == "auto" and source_size > threshold):
        return "none", source, source_size, source_size, hash_file(source)

    temp_path = temp_dir / (str(token) + ".gz")
    raw_size = 0
    digest = hashlib.sha256()

    with source.open("rb") as src, temp_path.open("wb") as raw_out:
        with gzip.GzipFile(
            filename="",
            mode="wb",
            fileobj=raw_out,
            compresslevel=6,
            mtime=0,
        ) as gz:
            for chunk in iter(lambda: src.read(8 * 1024 * 1024), b""):
                raw_size += len(chunk)
                digest.update(chunk)
                gz.write(chunk)

    stored_size = temp_path.stat().st_size
    if policy == "auto" and stored_size >= raw_size:
        temp_path.unlink()
        return "none", source, raw_size, raw_size, digest.hexdigest()

    return "gzip", temp_path, raw_size, stored_size, digest.hexdigest()


def copy_payload(source: Path, output) -> None:
    with source.open("rb") as src:
        shutil.copyfileobj(src, output, length=8 * 1024 * 1024)


def build(args: argparse.Namespace) -> Path:
    root = Path(args.input).resolve()
    if not root.is_dir():
        raise PackageError("input is not a directory: " + str(root))

    output = Path(args.output) if args.output else default_output(root)
    output.parent.mkdir(parents=True, exist_ok=True)

    if output.resolve() == root:
        raise PackageError("output cannot be the input directory")

    boot_path, boot_package = resolve_role(
        root, args.boot, "boot", "boot.wasm", ("boot.wasm",)
    )
    image_path, image_package = resolve_role(
        root, args.image, "image", "image.bin", ("isaac.segs.bin", "image.bin")
    )
    trail_path, trail_package = resolve_role(
        root, args.trail, "trail", "boot-trail.json", ("boot-trail.json",)
    )

    candidates: list[tuple[str, Path, str]] = []
    reserved_sources: set[Path] = set()

    guest_package: str | None = None
    guest_dll_packages: list[str] = []
    zapi_packages: list[str] = []
    zdll_packages: list[str] = []
    extra_roles: list[tuple[str, Path, str]] = []
    if args.guest:
        guest_path = Path(args.guest).resolve()
        if not guest_path.is_file():
            raise PackageError("guest file does not exist: " + str(guest_path))
        guest_package = "zwasm_guest/guest.pe"
        extra_roles.append((guest_package, guest_path, "guest"))
    seen_names: set[str] = set()
    for item in args.guest_dll:
        dll_path = Path(item).resolve()
        if not dll_path.is_file():
            raise PackageError("guest dll does not exist: " + str(dll_path))
        if dll_path.name.lower() in seen_names:
            raise PackageError("duplicate guest dll name: " + dll_path.name)
        seen_names.add(dll_path.name.lower())
        pkg = "zwasm_guest/dlls/" + dll_path.name
        guest_dll_packages.append(pkg)
        extra_roles.append((pkg, dll_path, "guest-dll"))
    for item in args.zapi:
        zapi_path = Path(item).resolve()
        if not zapi_path.is_file():
            raise PackageError("zapi file does not exist: " + str(zapi_path))
        pkg = "zwasm_guest/zapi/" + zapi_path.name
        zapi_packages.append(pkg)
        extra_roles.append((pkg, zapi_path, "zapi"))
    for item in args.zdll:
        zdll_path = Path(item).resolve()
        if not zdll_path.is_file():
            raise PackageError("zdll file does not exist: " + str(zdll_path))
        pkg = "zwasm_guest/zdlls/" + zdll_path.name
        zdll_packages.append(pkg)
        extra_roles.append((pkg, zdll_path, "zdll"))
    for pkg, path, role in extra_roles:
        candidates.append((pkg, path, role))
        reserved_sources.add(path.resolve())

    for path, package_name, role in (
        (boot_path, boot_package, "boot"),
        (image_path, image_package, "image"),
        (trail_path, trail_package, "trail"),
    ):
        if path is not None and package_name is not None:
            candidates.append((package_name, path, role))
            reserved_sources.add(path.resolve())

    for package_path, path in iter_instance_files(
        root, args.include_native, args.exclude
    ):
        if path.resolve() in reserved_sources:
            continue
        candidates.append((package_path, path, "instance"))

    if not candidates:
        raise PackageError("no files selected for the package")

    entries: list[dict] = []

    with tempfile.TemporaryDirectory(prefix="zwasm-") as tmp:
        temp_dir = Path(tmp)
        prepared: list[tuple[dict, Path]] = []

        for token, (package_path, source_path, kind) in enumerate(candidates):
            compression, stored_path, raw_size, stored_size, digest = prepare_payload(
                source_path,
                args.gzip,
                args.gzip_threshold,
                temp_dir,
                token,
            )
            entry = {
                "path": package_path,
                "kind": kind,
                "sourceName": source_path.name,
                "offset": 0,
                "size": raw_size,
                "storedSize": stored_size,
                "compression": compression,
                "sha256": digest,
                "mode": 0o644,
            }
            entries.append(entry)
            prepared.append((entry, stored_path))

        manifest = {
            "schema": "zwasm.package/1",
            "formatVersion": VERSION,
            "name": root.name,
            "createdUtc": dt.datetime.now(dt.timezone.utc).replace(microsecond=0).isoformat(),
            "source": {"name": root.name, "fileCount": len(entries)},
            "boot": boot_package,
            "image": image_package,
            "trail": trail_package,
            "guest": guest_package,
            "guestDlls": guest_dll_packages,
            "zapi": zapi_packages,
            "zdlls": zdll_packages,
            "entries": entries,
        }

        index_blob = b""
        payload_offset = 0
        for _ in range(16):
            index_blob = json.dumps(
                manifest,
                ensure_ascii=False,
                separators=(",", ":"),
                sort_keys=True,
            ).encode("utf-8")
            payload_offset = (
                (HEADER_SIZE + len(index_blob) + PAGE_SIZE - 1) // PAGE_SIZE
            ) * PAGE_SIZE

            offset = payload_offset
            for entry, stored_path in prepared:
                entry["offset"] = offset
                offset += entry["storedSize"]

            new_blob = json.dumps(
                manifest,
                ensure_ascii=False,
                separators=(",", ":"),
                sort_keys=True,
            ).encode("utf-8")
            if new_blob == index_blob:
                index_blob = new_blob
                break
            index_blob = new_blob
        else:
            raise PackageError("manifest index did not converge")

        with output.open("wb") as f:
            f.write(
                HEADER.pack(
                    MAGIC,
                    VERSION,
                    0,
                    HEADER_SIZE,
                    len(index_blob),
                    payload_offset,
                    len(entries),
                    b"",
                )
            )
            f.write(index_blob)
            f.write(b"\0" * (payload_offset - f.tell()))
            for entry, stored_path in prepared:
                if f.tell() != entry["offset"]:
                    raise PackageError(
                        "internal offset error for "
                        + entry["path"]
                        + ": "
                        + str(f.tell())
                        + " != "
                        + str(entry["offset"])
                    )
                copy_payload(stored_path, f)

    print("[ZWASM] wrote " + str(output))
    print("[ZWASM] entries: " + str(len(entries)))
    print("[ZWASM] bytes:   " + str(output.stat().st_size))
    print("[ZWASM] boot:    " + (manifest["boot"] or "(none)"))
    print("[ZWASM] image:   " + (manifest["image"] or "(none)"))
    print("[ZWASM] guest:   " + (manifest["guest"] or "(none)"))
    print("[ZWASM] dlls:    " + str(len(manifest["guestDlls"])))
    print("[ZWASM] zapi:    " + str(len(manifest["zapi"])))
    print("[ZWASM] zdlls:   " + str(len(manifest["zdlls"])))
    return output

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Pack a directory into a ZWASM .zgame"
    )
    p.add_argument("input", help="game/resource directory")
    p.add_argument("--output", "-o", help="output .zgame path")
    p.add_argument("--boot", help="browser-ready boot.wasm to embed")
    p.add_argument("--image", help="prepared memory image to embed")
    p.add_argument("--trail", help="boot trail JSON to embed")
    p.add_argument("--guest", help="PE32 game executable to embed as zwasm_guest/guest.pe")
    p.add_argument("--guest-dll", action="append", default=[], help="bundled guest DLL (repeatable)")
    p.add_argument("--zapi", action="append", default=[], help="ZWASM API manifest to embed (repeatable)")
    p.add_argument("--xapi", action="append", default=[], help="legacy .xapi compatibility alias")
    p.add_argument("--zdll", action="append", default=[], help="ZWASM WASM DLL container to embed (repeatable)")
    p.add_argument("--exclude", action="append", default=[], help="glob to exclude")
    p.add_argument(
        "--include-native",
        action="store_true",
        help="include native .exe/.dll/.pdb/etc. files",
    )
    p.add_argument(
        "--gzip", choices=("auto", "always", "never"), default="auto"
    )
    p.add_argument(
        "--gzip-threshold",
        type=int,
        default=16 * 1024 * 1024,
        help="auto mode only compresses files up to this size",
    )
    args = p.parse_args()
    args.zapi.extend(args.xapi)
    return args


def main() -> int:
    try:
        build(parse_args())
        return 0
    except PackageError as exc:
        print("[ZWASM] ERROR: " + str(exc))
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
